### PR TITLE
Replace really sad face

### PR DESCRIPTION
**Pull request by AdrianaCeric**
Addresses https://github.com/ibi-group/survey/issues/10

### CODE REVIEW

**Review by miles-grant-ibigroup — APPROVED** [review]
Love it! I am wondering if we can find an emoji that's always yellow that has eyes more similar to the others I tried to find emoji with similar eyes but it's not that big a deal!

**Comment by AdrianaCeric** [comment]
I wanna use this one: 
image
but it turns into this: 
image
We could also use: 😵‍💫😫

**Comment by miles-grant-ibigroup** [comment]
Let's stick with the tear maybe... better support than the other 2. Don't want any boxes!

**Review by daniel-heppner-ibigroup — APPROVED** [review]
Can't believe unicode would fail us like this.

**Pull request merged**
